#!/bin/sh -e

check_passed=0

run_check() {
	if [ "${check_passed}" -ne 0 ]; then
		return
	fi

	./manage.py check --deploy

	check_passed=1
}

main() {
	BASENAME="$(basename "$0")"

	if [ "$#" -lt 1 ]; then
		echo "Usage: ${BASENAME} COMMAND..."
		echo
		echo "Available commands are:"
		echo
		echo "  migrate     Runs Django migrations"
		echo "  runserver   Collects static files and starts uWSGI server"
		echo
		exit
	fi

	for command in "$@"; do
		case "${command}" in
			"migrate")
				run_check

				# Several migrations write to the media directory
				./manage.py migrate --no-input
				;;
			"runserver")
				run_check

				chmod -R u+w /srv/taiga-back/static
				./manage.py collectstatic --no-input
				chmod -R a-w /srv/taiga-back/static

				exec uwsgi /usr/local/etc/uwsgi/uwsgi.ini
				;;
			*)
				echo "Unknown ${BASENAME} command '${command}'." >&2
				exit 1
				;;
		esac
	done
}

main "$@"
